import { PageIntro, RepoLink, Steps } from "../components/UI";
import { dev } from "../lib/results";

export default function ReproPage(){return <div className="section-shell page"><PageIntro eyebrow="REPRODUCIBILITY · 可重現性" title="每個展示數字都能追到資料與設定"><p>Reproducibility（可重現性）代表其他人能依照同樣步驟得到相同結果。Python 負責資料與模型計算，GitHub Actions 可自動執行；GitHub Pages 只展示 Next.js 預先產生的靜態網頁與已驗證 JSON 結果檔，不會在訪客瀏覽時偷偷重算。</p></PageIntro><section className="content-section"><h2>本機重現｜自己重新跑一次</h2><p className="body-copy">以下指令會建立獨立 Python 環境、安裝專案、重跑開發期與最終測試實驗，再建置網站。這一頁主要提供給想驗證程式的技術讀者；一般讀者只要知道，網站數字不是手動填入，而是由這套固定流程產生。</p><div className="code-block"><code>python -m venv .venv</code><code>.venv/Scripts/pip install -e &quot;.[dev]&quot;</code><code>lottery-ml experiments development --root .</code><code>lottery-ml experiments holdout --root .</code><code>cd web &amp;&amp; pnpm install &amp;&amp; pnpm build</code></div></section><section className="content-section"><h2>Lineage checks｜確認每一步使用同一版本</h2><Steps items={[
  ["01","Dataset hash｜資料指紋",`${dev.data_sha256}。SHA-256 可確認資料內容是否完全相同。`],
  ["02","Feature schema｜特徵規格",`Feature version ${dev.feature_version}，固定計算窗口與欄位順序，避免同名特徵在不同時間代表不同東西。`],
  ["03","Environment｜執行環境",`${Object.entries(dev.package_versions).map(([k,v])=>`${k} ${v}`).join(" · ")}。保存套件版本，降低軟體更新造成結果不同的風險。`],
  ["04","Selection freeze｜先鎖定再驗收",<><RepoLink path="configs/experiments/selection-v1.json">selection-v1.json</RepoLink> 記錄開發結果的 SHA 指紋；若內容不一致，holdout 會直接停止（fail closed），避免看完考題才改答案。</>],
]}/></section><section className="content-section"><h2>文件索引｜想深入時從這裡開始</h2><ul className="clean-list"><li><RepoLink path="docs/system-design.md"><code>docs/system-design.md</code></RepoLink> — 系統架構與資料如何流動</li><li><RepoLink path="docs/ml-methodology.md"><code>docs/ml-methodology.md</code></RepoLink> — 特徵、時間交叉驗證、模型與評估指標</li><li><RepoLink path="docs/model-card.md"><code>docs/model-card.md</code></RepoLink> — 模型適用範圍、限制與最終結果</li><li><RepoLink path="docs/data-pipeline.md"><code>docs/data-pipeline.md</code></RepoLink> — 資料匯入與版本備份規則</li></ul></section></div>}
